# Generated by Django 5.2.12 on 2026-03-30 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color_hex', models.CharField(default='#2E7D32', help_text='Color para las etiquetas (ej: #FF0000)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rival', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(default='Estadio Principal', max_length=200)),
                ('es_local', models.BooleanField(default=True)),
                ('link_entradas', models.URLField(blank=True, help_text='Opcional: Link a la ticketera', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar el partido')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='deportes.disciplina')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
