# Generated by Django 5.2.12 on 2026-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='resultado_arbolito',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Goles/Puntos de Arbolito. Dejar en blanco si aún no se jugó.', null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado_rival',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Goles/Puntos del Rival. Dejar en blanco si aún no se jugó.', null=True),
        ),
    ]
