# Generated by Django 5.2.12 on 2026-03-31 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0002_partido_resultado_arbolito_partido_resultado_rival'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Información sobre la disciplina, horarios, etc.'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='deportes/portadas/'),
        ),
        migrations.CreateModel(
            name='ImagenDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='deportes/galeria/%Y/%m/')),
                ('epigrafe', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar las fotos en la galería.')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='deportes.disciplina')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['orden'],
            },
        ),
    ]
