# Generated by Django 5.2.12 on 2026-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0003_disciplina_descripcion_disciplina_imagen_portada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['fecha_hora'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterField(
            model_name='partido',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarcar para ocultar el partido'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True),
        ),
    ]
