# Generated by Django 5.2.12 on 2026-03-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(help_text='Sin puntos ni espacios', max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField(blank=True, help_text='¿Alguna consulta adicional?')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de contacto'), ('contactado', 'Contactado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Socio',
                'verbose_name_plural': 'Solicitudes de Socios',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
