# Generated by Django 5.2.12 on 2026-04-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_consultacontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultacontacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
