# Generated by Django 5.2.12 on 2026-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_consultacontacto_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultacontacto',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Consulta de Contacto', 'verbose_name_plural': 'Consultas de Contacto'},
        ),
        migrations.AlterField(
            model_name='consultacontacto',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='consultacontacto',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='solicitudsocio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de contacto'), ('contactado', 'Contactado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudsocio',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
