# Generated by Django 5.2.12 on 2026-03-30 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Opcional. Texto que aparece sobre la imagen.', max_length=100)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para elegir qué foto aparece primero.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Imágenes de Carrusel',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('bajada', models.TextField(help_text='Resumen corto para la tarjeta de la página principal.')),
                ('cuerpo', models.TextField(help_text='Contenido completo de la noticia.')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='noticias/%Y/%m/')),
                ('es_destacada', models.BooleanField(default=False, help_text='¿Mostrar en la columna central de novedades?')),
                ('fecha_publicacion', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True, help_text='Permite ocultar la noticia sin borrarla de la base de datos (Soft Delete).')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='institucion.categoria')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
