# Generated by Django 5.2.12 on 2026-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Pie de foto o descripción del video', max_length=250)),
                ('imagen', models.ImageField(blank=True, help_text='Subir foto (JPG/PNG)', null=True, upload_to='institucion/galeria/img/')),
                ('video', models.FileField(blank=True, help_text='Subir video (idealmente MP4 corto). Si subís video, dejá la imagen en blanco.', null=True, upload_to='institucion/galeria/vid/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de Galería',
                'verbose_name_plural': 'Galería Multimedia',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
