# Generated by Django 5.2.12 on 2026-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencarrusel',
            name='imagen',
            field=models.ImageField(help_text='ATENCIÓN: Para que no se corte, subir fotos horizontales (apaisadas). Tamaño recomendado: 1920x1080 píxeles.', upload_to='carrusel/'),
        ),
    ]
