# Generated by Django 5.2.12 on 2026-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_alter_imagencarrusel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencarrusel',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='video',
            field=models.FileField(blank=True, help_text='Subir video (idealmente MP4 corto).', null=True, upload_to='institucion/galeria/vid/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Permite ocultar la noticia sin borrarla de la base de datos (Soft Delete).'),
        ),
    ]
